<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\PCOptimizer-v6.ico</ApplicationIcon>
    <AssemblyName>PCOptimizer</AssemblyName>
    <Product>PC Optimizer</Product>
    <AssemblyTitle>PC Optimizer</AssemblyTitle>
    <Version>6.1.0</Version>
    <AssemblyVersion>6.1.0.0</AssemblyVersion>
    <FileVersion>6.1.0.0</FileVersion>
  </PropertyGroup>
</Project>